// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Highlight struct {
	ID        pgtype.UUID      `json:"id"`
	SessionID pgtype.UUID      `json:"session_id"`
	Text      string           `json:"text"`
	Position  int32            `json:"position"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Interaction struct {
	ID          pgtype.UUID      `json:"id"`
	HighlightID pgtype.UUID      `json:"highlight_id"`
	Question    string           `json:"question"`
	Answer      pgtype.Text      `json:"answer"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Session struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	Status    string           `json:"status"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
