// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateHighlight(ctx context.Context, arg CreateHighlightParams) (Highlight, error)
	CreateInteraction(ctx context.Context, arg CreateInteractionParams) (Interaction, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteHighlightsBySession(ctx context.Context, sessionID pgtype.UUID) error
	DeleteInteractionsByHighlight(ctx context.Context, highlightID pgtype.UUID) error
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	GetHighlight(ctx context.Context, id pgtype.UUID) (Highlight, error)
	GetHighlightsBySession(ctx context.Context, sessionID pgtype.UUID) ([]Highlight, error)
	GetInteraction(ctx context.Context, id pgtype.UUID) (Interaction, error)
	GetInteractionByHighlight(ctx context.Context, highlightID pgtype.UUID) (Interaction, error)
	GetInteractionsByHighlight(ctx context.Context, highlightID pgtype.UUID) ([]Interaction, error)
	GetSession(ctx context.Context, id pgtype.UUID) (Session, error)
	ListSessions(ctx context.Context) ([]Session, error)
	UpdateInteractionAnswer(ctx context.Context, arg UpdateInteractionAnswerParams) (Interaction, error)
	UpdateInteractionQuestion(ctx context.Context, arg UpdateInteractionQuestionParams) (Interaction, error)
	UpdateSessionName(ctx context.Context, arg UpdateSessionNameParams) (Session, error)
	UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error
}

var _ Querier = (*Queries)(nil)
